import type { Product } from "@/components/product-card"

export const products: Product[] = [
  {
    id: "panel-450",
    name: "EclipseMax 450W Mono Panel",
    category: "Solar Panels",
    image: "/product-panel.png",
    description: "High-efficiency monocrystalline panel engineered for South African sun.",
    specs: ["450W output", "21.3% efficiency", "25-year warranty"],
    price: 2450,
    salePrice: 1950,
    badge: "Best Seller",
  },
  {
    id: "panel-550",
    name: "EclipseMax 550W Bifacial",
    category: "Solar Panels",
    image: "/product-panel.png",
    description: "Premium bifacial panel capturing light from both sides for extra yield.",
    specs: ["550W output", "Bifacial gain +15%", "30-year linear warranty"],
    price: 3200,
    salePrice: 2850,
  },
  {
    id: "inverter-5kw",
    name: "EclipseHybrid 5kW Inverter",
    category: "Inverters",
    image: "/product-inverter.png",
    description: "Smart hybrid inverter with seamless grid and battery switching.",
    specs: ["5kW continuous", "WiFi monitoring", "Load-shedding ready"],
    price: 18500,
  },
  {
    id: "inverter-8kw",
    name: "EclipseHybrid 8kW Inverter",
    category: "Inverters",
    image: "/product-inverter.png",
    description: "Powerful three-phase hybrid inverter for larger homes and businesses.",
    specs: ["8kW continuous", "Parallel capable", "Surge protection"],
    price: 32000,
    salePrice: 28500,
    badge: "Sale",
  },
  {
    id: "battery-5kwh",
    name: "EclipseStore 5.12kWh Battery",
    category: "Lithium Batteries",
    image: "/product-battery.png",
    description: "Wall-mounted LiFePO4 battery for reliable backup and self-consumption.",
    specs: ["5.12kWh usable", "6000+ cycles", "10-year warranty"],
    price: 26500,
    salePrice: 23999,
  },
  {
    id: "battery-10kwh",
    name: "EclipseStore 10.24kWh Battery",
    category: "Lithium Batteries",
    image: "/product-battery.png",
    description: "High-capacity stackable battery for extended whole-home backup.",
    specs: ["10.24kWh usable", "Stackable design", "Smart BMS"],
    price: 48000,
    badge: "Limited Stock",
  },
  {
    id: "kit-residential",
    name: "Home Starter Solar Kit",
    category: "Solar Kits",
    image: "/product-kit.png",
    description: "Everything a household needs to start saving — panels, inverter & battery.",
    specs: ["5kW system", "Plug-and-play design", "Installation included"],
    price: 95000,
    salePrice: 85000,
    badge: "Best Seller",
  },
  {
    id: "kit-premium",
    name: "Premium Backup Solar Kit",
    category: "Solar Kits",
    image: "/product-kit.png",
    description: "Complete whole-home backup solution for total energy independence.",
    specs: ["8kW system", "10kWh storage", "Full backup ready"],
    price: 165000,
  },
  {
    id: "acc-mounting",
    name: "Pro Mounting & Cable Kit",
    category: "Accessories",
    image: "/product-accessory.png",
    description: "Premium aluminium mounting rails, brackets and certified solar cabling.",
    specs: ["Corrosion resistant", "Tile & sheet roof", "MC4 connectors"],
    price: 4500,
  },
  {
    id: "acc-monitor",
    name: "Smart Energy Monitor",
    category: "Accessories",
    image: "/product-accessory.png",
    description: "Real-time energy monitoring device with mobile app integration.",
    specs: ["Live tracking", "App alerts", "Easy install"],
    price: 1200,
  },
]

export const productCategories = [
  "All",
  "Solar Panels",
  "Inverters",
  "Lithium Batteries",
  "Solar Kits",
  "Accessories",
]

export const packages = [
  {
    id: "residential",
    title: "Residential Solar",
    image: "/residential-solar.png",
    description: "Tailored systems that cut your home's electricity bill and beat load-shedding.",
    features: ["3–10kW systems", "Battery backup", "App monitoring"],
  },
  {
    id: "commercial",
    title: "Commercial Solar",
    image: "/commercial-solar.png",
    description: "Scalable installations that reduce operating costs and boost sustainability.",
    features: ["High-yield arrays", "Fast payback", "Reduced demand charges"],
  },
  {
    id: "hybrid",
    title: "Hybrid Systems",
    image: "/hybrid-solar.png",
    description: "The best of both worlds — grid-tied savings with battery backup security.",
    features: ["Grid + battery", "Seamless switching", "Energy independence"],
  },
  {
    id: "backup",
    title: "Backup Power Systems",
    image: "/backup-power.png",
    description: "Reliable lithium battery backup to keep your essentials running 24/7.",
    features: ["Instant switchover", "Silent operation", "Expandable storage"],
  },
]
